import Head from 'next/head'
import { Inter } from '@next/font/google'
import type { ReactElement } from 'react'
import type { NextPageWithLayout } from './_app'
import MainLayout from '../components/layouts/MainLayout'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <div className="auth-wrapper d-flex no-block justify-content-center align-items-center position-relative"
            style={{background:"url(/assets/images/big/auth-bg.jpg) no-repeat center center;"}}>
            <div className="auth-box row">
                <div className="col-lg-7 col-md-5 modal-bg-img" style={{ background: "url(/assets/images/big/3.jpg)" }}>
                </div>
                <div className="col-lg-5 col-md-7 bg-white">
                    <div className="p-3">
                        <div className="text-center">
                            <img src="/assets/images/big/icon.png" alt="wrapkit"/>
                        </div>
                        <h2 className="mt-3 text-center">Sign In</h2>
                        <p className="text-center">Enter your email address and password to access admin panel.</p>
                        <form className="mt-4">
                            <div className="row">
                                <div className="col-lg-12">
                                    <div className="form-group">
                                        <label className="text-dark" htmlFor="uname">Username</label>
                                        <input className="form-control" id="uname" type="text"
                                            placeholder="enter your username" />
                                    </div>
                                </div>
                                <div className="col-lg-12">
                                    <div className="form-group">
                                        <label className="text-dark" htmlFor="pwd">Password</label>
                                        <input className="form-control" id="pwd" type="password"
                                            placeholder="enter your password"/>
                                    </div>
                                </div>
                                <div className="col-lg-12 text-center">
                                    <button type="submit" className="btn btn-block btn-dark">Sign In</button>
                                </div>
                                <div className="col-lg-12 text-center mt-5">
                                    Do not have an account? <a href="#" className="text-danger">Sign Up</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
      </main>
    </>
  )
}

Home.getLayout = function getLayout(page: ReactElement) {
    return (
      <MainLayout>
        {page}
      </MainLayout>
    )
  }